allowBuilds:
  '@parcel/watcher': true
  '@scarf/scarf': false
  esbuild: true
  lmdb: true
  msgpackr-extract: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - lmdb
  - msgpackr-extract
